[package]
name = "rotatory"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[features]
default = []
async = []
sync = []
