on: [ push ]

name: build

jobs:
  rust_build:
    name: Rust build
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.72.1
        features:
          - "async_std"
          - "async_tokio"
          - "async_std,async_tokio"
          - "sync"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          default: true
          override: true
          components: clippy

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features ${{ matrix.features }} --all-targets -- -D warnings

      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features ${{ matrix.features }} --all-targets


  check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: --check
