on: [ push, pull_request ]

name: build

jobs:
  rust_build:
    name: Rust build
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.72.1
        profile:
          - dev
          - release
        feature_async_std: [ "", "async_std" ]
        feature_async_tokio: [ "", "async_tokio" ]
        feature_sync: [ "", "sync" ]
    runs-on: ubuntu-latest
    env:
      FEATURES: ${{ matrix.feature_async_std }},${{ matrix.feature_async_tokio }},${{ matrix.feature_sync }},
    steps:
      - uses: actions/checkout@v4

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          default: true
          override: true
          components: clippy

      - name: Clippy
        run: cargo clippy --profile ${{ matrix.profile }} --features $FEATURES --all-targets -- -D warnings

      - name: Tests
        run: cargo test --profile ${{ matrix.profile }} --features $FEATURES --all-targets

      - name: Build
        run: cargo build --profile ${{ matrix.profile }} --features $FEATURES --all-targets

  check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: --check
