on: [ push, pull_request ]

name: build

jobs:
  rust_build:
    name: Rust build
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.72.1
        profile:
          - dev
          - release
        feature_async_std: [ "", "async_std" ]
        feature_async_tokio: [ "", "async_tokio" ]
        feature_sync: [ "", "sync" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          default: true
          override: true
          components: clippy

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --profile ${{ matrix.profile }} --features "${{ matrix.feature_async_std }},${{ matrix.feature_async_tokio }},${{ matrix.feature_sync }}," --all-targets -- -D warnings

      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --profile ${{ matrix.profile }} --features "${{ matrix.async_std }},${{ matrix.async_tokio }},${{ matrix.sync }}," --all-targets

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile ${{ matrix.profile }} --features "${{ matrix.async_std }},${{ matrix.async_tokio }},${{ matrix.sync }}," --all-targets

  check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: --check
